# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tech0-gen8-step4-pos-app-113

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      # 1) ソースコードをチェックアウト
      - uses: actions/checkout@v4

      # 2) Node.js のセットアップ
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3) npm install & build & test
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # 4) ビルド成果物を deploy フォルダにまとめる  ←★追加★
      - name: Copy artifact for deployment job
        run: |
          mkdir deploy
          # .next/standalone の中身を deploy/ 直下へコピー
          cp -r ./.next/standalone/* ./deploy
          # public フォルダがあればコピー
          if [ -d "./public" ]; then cp -r ./public ./deploy; fi
          # .next/static があれば deploy/.next/static にコピー
          mkdir -p ./deploy/.next
          if [ -d "./.next/static" ]; then cp -r ./.next/static ./deploy/.next/static; fi

      # 5) deploy フォルダを ZIP 化  ←★修正★
      - name: Zip artifact for deployment
        run: zip release.zip ./deploy -r

      # 6) アーティファクトをアップロード
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # 7) アーティファクトをダウンロード
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 8) ZIP を解凍
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      # 9) Azure Web App へデプロイ
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen8-step4-pos-app-113'
          slot-name: 'Production'
          # package を . から ./deploy に変更  ←★修正★
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_39476555C0454AF8943766C12B9C78A5 }}
